# Generated by Django 3.2.6 on 2023-07-15 22:36

from django.db import migrations, models
from productos.models.Departamentos import Departamentos

def cargar_departamentos(apps, schema_editor):
    departamento = Departamentos(nombre='Cuidado Facial', descripcion='')
    departamento.save()

    departamento = Departamentos(nombre='Cuidado Personal', descripcion='')
    departamento.save()

    departamento = Departamentos(nombre='Cabello', descripcion='')
    departamento.save()

    departamento = Departamentos(nombre='Uñas', descripcion='')
    departamento.save()

    departamento = Departamentos(nombre='Maquillaje', descripcion='')
    departamento.save()

    departamento = Departamentos(nombre='Fragancias', descripcion='')
    departamento.save()

    departamento = Departamentos(nombre='Cosmeticos Hombre', descripcion='')
    departamento.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'departamentos',
            },
        ),
        migrations.RunPython(cargar_departamentos),
    ]
