# Generated by Django 3.2.6 on 2023-07-16 19:10

from django.db import migrations, models
import django.db.models.deletion
from productos.models.Productos import Productos
from productos.models.DescuentoProductos import DescuentoProductos
from productos.models.ColoresProductos import ColoresProductos

def cargar_datos(apps, schema_editor):

    producto = Productos(nombre='FRAGANCIA WHITE', descripcion='', imagen='', departamento_id=6, cantidad=1500, valor_unitario=28000)
    producto.save()

    departamento = Productos(nombre='FRAGANCIA EU TOILETTE SWEET', descripcion='', imagen='', departamento_id=6, cantidad=1500, valor_unitario=18000)
    departamento.save()

    departamento = Productos(nombre='FRAGANCIAS EU TOILETTE', descripcion='', imagen='', departamento_id=6, cantidad=1500, valor_unitario=20000)
    departamento.save()

    departamento = Productos(nombre='FRAGANCIA PARADISE', descripcion='', imagen='', departamento_id=6, cantidad=1500, valor_unitario=30000)
    departamento.save()

    departamento = Productos(nombre='FRAGANCIA EXHUBERANT', descripcion='', imagen='', departamento_id=6, cantidad=1500, valor_unitario=30000)
    departamento.save()

    departamento = Productos(nombre='FRAGANCIA SPECIAL MOMENT', descripcion='', imagen='', departamento_id=6, cantidad=1500, valor_unitario=30000)
    departamento.save()

    departamento = Productos(nombre='FRAGANCIA SPECIAL MOMENT MEMORY', descripcion='', imagen='', departamento_id=6, cantidad=1500, valor_unitario=24000)
    departamento.save()

    departamento = Productos(nombre='PROTEINA CAPILAR', descripcion='', imagen='', departamento_id=3, cantidad=1500, valor_unitario=52000)
    departamento.save()

    departamento = Productos(nombre='SHAMPOO CEBOLLA', descripcion='', imagen='', departamento_id=3, cantidad=1500, valor_unitario=23000)
    departamento.save()

    departamento = Productos(nombre='TRATAMIENTO DE CEBOLLA', descripcion='', imagen='', departamento_id=3, cantidad=1500, valor_unitario=27000)
    departamento.save()

    departamento = Productos(nombre='SILICONA RESTAURADORA', descripcion='', imagen='', departamento_id=3, cantidad=1500, valor_unitario=12000)
    departamento.save()

    departamento = Productos(nombre='SHAMPOO', descripcion='', imagen='', departamento_id=3, cantidad=1500, valor_unitario=12000)
    departamento.save()

    departamento = Productos(nombre='ACONDICIONADOR', descripcion='', imagen='', departamento_id=3, cantidad=1500, valor_unitario=12000)
    departamento.save()

    departamento = Productos(nombre='DESMAQUILLADOR ROSAS', descripcion='', imagen='', departamento_id=5, cantidad=1500, valor_unitario=17000)
    departamento.save()

    departamento = Productos(nombre='BASE LÍQUIDA PERFECT COVER', descripcion='', imagen='', departamento_id=5, cantidad=1500, valor_unitario=20000)
    departamento.save()

    departamento = Productos(nombre='LAPIZ DE LABIOS PERFECT LIPLINER', descripcion='', imagen='', departamento_id=5, cantidad=1500, valor_unitario=10000)
    departamento.save()

    departamento = Productos(nombre='TÓNICO DE ROSAS + COLÁGENO', descripcion='', imagen='', departamento_id=5, cantidad=1500, valor_unitario=13000)
    departamento.save()

    departamento = Productos(nombre='CORRECTOR MATTE COVERAGE', descripcion='', imagen='', departamento_id=5, cantidad=1500, valor_unitario=8000)
    departamento.save()

    departamento = Productos(nombre='MASCARILLA PEEL OF', descripcion='', imagen='', departamento_id=5, cantidad=1500, valor_unitario=12800)
    departamento.save()

    departamento = Productos(nombre='POLVO FULL PROTECTION', descripcion='', imagen='', departamento_id=5, cantidad=1500, valor_unitario=13600)
    departamento.save()

    departamento = Productos(nombre='LABIAL BARRA STAY COLOR', descripcion='', imagen='', departamento_id=5, cantidad=1500, valor_unitario=9600)
    departamento.save()

    departamento = Productos(nombre='PESTAÑINA EXTRA VOLUME', descripcion='', imagen='', departamento_id=5, cantidad=1500, valor_unitario=12800)
    departamento.save()

    departamento = Productos(nombre='DESODORANTE HOME', descripcion='', imagen='', departamento_id=7, cantidad=1500, valor_unitario=5600)
    departamento.save()

    departamento = Productos(nombre='DESODORANTE AQUASPORT', descripcion='', imagen='', departamento_id=7, cantidad=1500, valor_unitario=5600)
    departamento.save()

    departamento = Productos(nombre='FRAGANCIA NAVIGARE', descripcion='', imagen='', departamento_id=7, cantidad=1500, valor_unitario=26400)
    departamento.save()

    departamento = Productos(nombre='FRAGANCIA AQUASPORT', descripcion='', imagen='', departamento_id=7, cantidad=1500, valor_unitario=33000)
    departamento.save()

    departamento = Productos(nombre='FRAGANCIA TOILETTE', descripcion='', imagen='', departamento_id=7, cantidad=1500, valor_unitario=16000)
    departamento.save()

    departamento = Productos(nombre='Mascarilla Puntos Negros', descripcion='', imagen='', departamento_id=1, cantidad=1500, valor_unitario=1000)
    departamento.save()

    departamento = Productos(nombre='Mascarilla Colageno Para Labios Pilaten', descripcion='', imagen='', departamento_id=1, cantidad=1500, valor_unitario=2000)
    departamento.save()

    departamento = Productos(nombre='Extractor De Puntos Negros Digital Holy', descripcion='', imagen='', departamento_id=1, cantidad=1500, valor_unitario=70000)
    departamento.save()

    departamento = Productos(nombre='Masajeador Beauty Bar Holy', descripcion='', imagen='', departamento_id=1, cantidad=1500, valor_unitario=40000)
    departamento.save()

    departamento = Productos(nombre='Mascarilla De Aloe', descripcion='', imagen='', departamento_id=1, cantidad=1500, valor_unitario=4000)
    departamento.save()

    departamento = Productos(nombre='Mascarilla De Caracol', descripcion='', imagen='', departamento_id=1, cantidad=1500, valor_unitario=4000)
    departamento.save()

    departamento = Productos(nombre='Mascarilla Control Grasa', descripcion='', imagen='', departamento_id=1, cantidad=1500, valor_unitario=4000)
    departamento.save()

    departamento = Productos(nombre='Lip Mask De Propoleo', descripcion='', imagen='', departamento_id=1, cantidad=1500, valor_unitario=15000)
    departamento.save()

    departamento = Productos(nombre='Gua Sha Facial De Cuarzo Rosa Holy', descripcion='', imagen='', departamento_id=1, cantidad=1500, valor_unitario=30000)
    departamento.save()

    departamento = Productos(nombre='Agua De Hamamelis Pili', descripcion='', imagen='', departamento_id=1, cantidad=1500, valor_unitario=13000)
    departamento.save()

    departamento = Productos(nombre='Rodillo Facial De Cuarzo Rosa Holy', descripcion='', imagen='', departamento_id=1, cantidad=1500, valor_unitario=13000)
    departamento.save()

    departamento = Productos(nombre='Jabón Facial Piel Mixta O Normal', descripcion='', imagen='', departamento_id=1, cantidad=1500, valor_unitario=27000)
    departamento.save()

    departamento = Productos(nombre='Crema Contorno De Ojos', descripcion='', imagen='', departamento_id=1, cantidad=1500, valor_unitario=20000)
    departamento.save()

    departamento = Productos(nombre='Serum Gold Hidratante Y Reparador', descripcion='', imagen='', departamento_id=1, cantidad=1500, valor_unitario=20000)
    departamento.save()

    departamento = Productos(nombre='Loción Azufrada', descripcion='', imagen='', departamento_id=1, cantidad=1500, valor_unitario=20000)
    departamento.save()

    departamento = Productos(nombre='Piedra Volcánica En Roll On - Quita Grasa', descripcion='', imagen='', departamento_id=1, cantidad=1500, valor_unitario=16000)
    departamento.save()

    departamento = Productos(nombre='Depiladora 2 En 1 Holy', descripcion='', imagen='', departamento_id=2, cantidad=1500, valor_unitario=90000)
    departamento.save()

    departamento = Productos(nombre='Aro Led Selfie', descripcion='', imagen='', departamento_id=2, cantidad=1500, valor_unitario=6000)
    departamento.save()

    departamento = Productos(nombre='Depiladora 4 En 1', descripcion='', imagen='', departamento_id=2, cantidad=1500, valor_unitario=50000)
    departamento.save()

    departamento = Productos(nombre='Aceite De Almendras', descripcion='', imagen='', departamento_id=2, cantidad=1500, valor_unitario=17000)
    departamento.save()

    departamento = Productos(nombre='Mascarilla Exfoliante Para Pies', descripcion='', imagen='', departamento_id=2, cantidad=1500, valor_unitario=10000)
    departamento.save()

    departamento = Productos(nombre='Mascarilla Hidratante Para Piess', descripcion='', imagen='', departamento_id=2, cantidad=1500, valor_unitario=10000)
    departamento.save()

    departamento = Productos(nombre='Mascarilla Hidratante Para Manos', descripcion='', imagen='', departamento_id=2, cantidad=1500, valor_unitario=7000)
    departamento.save()

    departamento = Productos(nombre='Exfoliante Corporal De Pepino', descripcion='', imagen='', departamento_id=2, cantidad=1500, valor_unitario=22000)
    departamento.save()

    departamento = Productos(nombre='Removedor Recargable De Callos Para Pies', descripcion='', imagen='', departamento_id=2, cantidad=1500, valor_unitario=140000)
    departamento.save()

    departamento = Productos(nombre='Depilador Para Cejas Recargable', descripcion='', imagen='', departamento_id=2, cantidad=1500, valor_unitario=35000)
    departamento.save()

    departamento = Productos(nombre='Aceite Para Uñas', descripcion='', imagen='', departamento_id=4, cantidad=1500, valor_unitario=4000)
    departamento.save()

    departamento = Productos(nombre='Guantes De Protección Uv-Led Holy', descripcion='', imagen='', departamento_id=4, cantidad=1500, valor_unitario=4000)
    departamento.save()

    departamento = Productos(nombre='Lampara Para Uñas 54W', descripcion='', imagen='', departamento_id=4, cantidad=1500, valor_unitario=60000)
    departamento.save()

    departamento = Productos(nombre='Lampara Para Uñas 48W', descripcion='', imagen='', departamento_id=4, cantidad=1500, valor_unitario=50000)
    departamento.save()

    departamento = Productos(nombre='Lápiz Con Efecto Espejo Para Uñas', descripcion='', imagen='', departamento_id=4, cantidad=1500, valor_unitario=10000)
    departamento.save()

    departamento = Productos(nombre='Anillo De Resina Para Uñas Aurora', descripcion='', imagen='', departamento_id=4, cantidad=1500, valor_unitario=8000)
    departamento.save()

    departamento = Productos(nombre='Extractor De Polvo Para Uñas', descripcion='', imagen='', departamento_id=4, cantidad=1500, valor_unitario=80000)
    departamento.save()

    departamento = Productos(nombre='Esmalte Semipermanente Tonos Nude 7.3Ml Holy', descripcion='', imagen='', departamento_id=4, cantidad=1500, valor_unitario=15000)
    departamento.save()

    departamento = Productos(nombre='Lima Para Uñas 100/180', descripcion='', imagen='', departamento_id=4, cantidad=1500, valor_unitario=5000)
    departamento.save()

    departamento = Productos(nombre='Ultrabond Primer 7.3Ml Holy', descripcion='', imagen='', departamento_id=4, cantidad=1500, valor_unitario=15000)
    departamento.save()

    departamento = Productos(nombre='Esmalte Semipermanente Tonos Rosas 15Ml', descripcion='', imagen='', departamento_id=4, cantidad=1500, valor_unitario=25000)
    departamento.save()

    descuento = DescuentoProductos(producto_id=1, cantidad_minima=1, cantidad_maxima=50, valor=10)
    descuento.save()

    descuento = DescuentoProductos(producto_id=2, cantidad_minima=2, cantidad_maxima=50, valor=10)
    descuento.save()

    descuento = DescuentoProductos(producto_id=3, cantidad_minima=2, cantidad_maxima=50, valor=5)
    descuento.save()

    descuento = DescuentoProductos(producto_id=4, cantidad_minima=2, cantidad_maxima=50, valor=10)
    descuento.save()

    descuento = DescuentoProductos(producto_id=8, cantidad_minima=2, cantidad_maxima=50, valor=15)
    descuento.save()

    descuento = DescuentoProductos(producto_id=12, cantidad_minima=2, cantidad_maxima=50, valor=5)
    descuento.save()

    descuento = DescuentoProductos(producto_id=13, cantidad_minima=2, cantidad_maxima=50, valor=5)
    descuento.save()

    descuento = DescuentoProductos(producto_id=20, cantidad_minima=2, cantidad_maxima=50, valor=10)
    descuento.save()

    descuento = DescuentoProductos(producto_id=22, cantidad_minima=2, cantidad_maxima=50, valor=5)
    descuento.save()

    descuento = DescuentoProductos(producto_id=27, cantidad_minima=2, cantidad_maxima=50, valor=10)
    descuento.save()

    descuento = DescuentoProductos(producto_id=30, cantidad_minima=2, cantidad_maxima=50, valor=20)
    descuento.save()

    descuento = DescuentoProductos(producto_id=35, cantidad_minima=2, cantidad_maxima=50, valor=10)
    descuento.save()

    descuento = DescuentoProductos(producto_id=36, cantidad_minima=2, cantidad_maxima=50, valor=10)
    descuento.save()

    descuento = DescuentoProductos(producto_id=44, cantidad_minima=2, cantidad_maxima=50, valor=10)
    descuento.save()

    descuento = DescuentoProductos(producto_id=52, cantidad_minima=2, cantidad_maxima=50, valor=10)
    descuento.save()

    color = ColoresProductos(producto_id=1, color='#E4E6EF')
    color.save()

    color = ColoresProductos(producto_id=2, color='#E4E6EF')
    color.save()

    color = ColoresProductos(producto_id=3, color='#E4E6EF')
    color.save()

    color = ColoresProductos(producto_id=4, color='#E4E6EF')
    color.save()

    color = ColoresProductos(producto_id=5, color='#E4E6EF')
    color.save()

    color = ColoresProductos(producto_id=6, color='#E4E6EF')
    color.save()

    color = ColoresProductos(producto_id=7, color='#E4E6EF')
    color.save()

    color = ColoresProductos(producto_id=8, color='#181C32')
    color.save()

    color = ColoresProductos(producto_id=9, color='#E4E6EF')
    color.save()

    color = ColoresProductos(producto_id=10, color='#20c997')
    color.save()

    color = ColoresProductos(producto_id=11, color='#F3F6F9')
    color.save()

    color = ColoresProductos(producto_id=12, color='#F3F6F9')
    color.save()

    color = ColoresProductos(producto_id=13, color='#F3F6F9')
    color.save()

    color = ColoresProductos(producto_id=14, color='#FFA800')
    color.save()

    color = ColoresProductos(producto_id=15, color='#F64E60')
    color.save()

    color = ColoresProductos(producto_id=16, color='#F3F6F9')
    color.save()

    color = ColoresProductos(producto_id=17, color='#F3F6F9')
    color.save()

    color = ColoresProductos(producto_id=18, color='#FFC8B7')
    color.save()

    color = ColoresProductos(producto_id=18, color='#FFAC92')
    color.save()

    color = ColoresProductos(producto_id=19, color='#3F4254')
    color.save()

    color = ColoresProductos(producto_id=20, color='#FFC8B7')
    color.save()

    color = ColoresProductos(producto_id=20, color='#FFAC92')
    color.save()

    color = ColoresProductos(producto_id=21, color='#FFAC92')
    color.save()

    color = ColoresProductos(producto_id=21, color='#fd7e14')
    color.save()

    color = ColoresProductos(producto_id=21, color='#F64E60')
    color.save()

    color = ColoresProductos(producto_id=22, color='#181C32')
    color.save()

    color = ColoresProductos(producto_id=23, color='#F3F6F9')
    color.save()

    color = ColoresProductos(producto_id=24, color='#F3F6F9')
    color.save()

    color = ColoresProductos(producto_id=25, color='#F3F6F9')
    color.save()

    color = ColoresProductos(producto_id=26, color='#F3F6F9')
    color.save()

    color = ColoresProductos(producto_id=27, color='#F3F6F9')
    color.save()

    color = ColoresProductos(producto_id=28, color='#181C32')
    color.save()

    color = ColoresProductos(producto_id=29, color='#FFAC92')
    color.save()

    color = ColoresProductos(producto_id=30, color='#fd7e14')
    color.save()

    color = ColoresProductos(producto_id=31, color='#fd7e14')
    color.save()

    color = ColoresProductos(producto_id=32, color='#20c997')
    color.save()

    color = ColoresProductos(producto_id=33, color='#FFAC92')
    color.save()

    color = ColoresProductos(producto_id=34, color='#3F4254')
    color.save()

    color = ColoresProductos(producto_id=35, color='#E5D3B0')
    color.save()

    color = ColoresProductos(producto_id=36, color='#FEC2E1')
    color.save()

    color = ColoresProductos(producto_id=37, color='#FFA800')
    color.save()

    color = ColoresProductos(producto_id=38, color='#FA8938')
    color.save()

    color = ColoresProductos(producto_id=39, color='#E4E6EF')
    color.save()

    color = ColoresProductos(producto_id=40, color='#E4E6EF')
    color.save()

    color = ColoresProductos(producto_id=41, color='#ffc107')
    color.save()

    color = ColoresProductos(producto_id=42, color='#F3F6F9')
    color.save()

    color = ColoresProductos(producto_id=43, color='#181C32')
    color.save()

    color = ColoresProductos(producto_id=44, color='#ffffff')
    color.save()

    color = ColoresProductos(producto_id=45, color='#ffffff')
    color.save()

    color = ColoresProductos(producto_id=45, color='#181C32')
    color.save()

    color = ColoresProductos(producto_id=45, color='#007bff')
    color.save()

    color = ColoresProductos(producto_id=45, color='#007bff')
    color.save()

    color = ColoresProductos(producto_id=46, color='#F64E60')
    color.save()

    color = ColoresProductos(producto_id=47, color='#FA0905')
    color.save()

    color = ColoresProductos(producto_id=48, color='#FFBBA0')
    color.save()

    color = ColoresProductos(producto_id=49, color='#FFBBA0')
    color.save()

    color = ColoresProductos(producto_id=50, color='#FFBBA0')
    color.save()

    color = ColoresProductos(producto_id=51, color='#20c997')
    color.save()

    color = ColoresProductos(producto_id=52, color='#FFBBA0')
    color.save()

    color = ColoresProductos(producto_id=53, color='#E4E6EF')
    color.save()

    color = ColoresProductos(producto_id=54, color='#E4E6EF')
    color.save()

    color = ColoresProductos(producto_id=55, color='#F64E60')
    color.save()

    color = ColoresProductos(producto_id=56, color='#F3F6F9')
    color.save()

    color = ColoresProductos(producto_id=57, color='#F3F6F9')
    color.save()

    color = ColoresProductos(producto_id=58, color='#FFA800')
    color.save()

    color = ColoresProductos(producto_id=58, color='#F3F6F9')
    color.save()

    color = ColoresProductos(producto_id=59, color='#ffffff')
    color.save()

    color = ColoresProductos(producto_id=59, color='#FFBBA0')
    color.save()

    color = ColoresProductos(producto_id=60, color='#FA73E7')
    color.save()

    color = ColoresProductos(producto_id=60, color='#FFA800')
    color.save()

    color = ColoresProductos(producto_id=61, color='#FA0905')
    color.save()

    color = ColoresProductos(producto_id=61, color='#E6634C')
    color.save()

    color = ColoresProductos(producto_id=61, color='#FFBBA0')
    color.save()

    color = ColoresProductos(producto_id=62, color='#F3F6F9')
    color.save()

    color = ColoresProductos(producto_id=63, color='#3F4254')
    color.save()

    color = ColoresProductos(producto_id=64, color='#FA0905')
    color.save()

    color = ColoresProductos(producto_id=64, color='#E6634C')
    color.save()

    color = ColoresProductos(producto_id=64, color='#FFBBA0')
    color.save()


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('imagen', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.departamentos')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='DescuentoProductos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_minima', models.IntegerField()),
                ('cantidad_maxima', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productos')),
            ],
            options={
                'db_table': 'descuento_productos',
            },
        ),
        migrations.CreateModel(
            name='ColoresProductos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=250)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productos')),
            ],
            options={
                'db_table': 'colores_productos',
            },
        ),
        migrations.RunPython(cargar_datos),
    ]
